# Workflow name
name: First Workflow

# Events
on: push

# Tasks to do
jobs:
  first-ob:
    runs-on: windows-latest
    steps:
      - name: Print greetings
        run: echo "Hello world"

      - name: Print Working"
        run: echo "Working"

      - name: Print Working2"
        run: echo "Working2"

      - name: Print Goodbye"
        run: echo "Goodbye"

      - name: Get code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry
        run: python -m pip install poetry==1.1.11

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      # load cached venv
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install depedencies
        run: python -m poetry install --no-interaction --no-root

      - name: Check depedencies
        run: |
          python -m poetry show
          poetry env info

      - name: Active venv
        run: |
          source $(poetry env info --path)/bin/activate
          poetry env info
          poetry env info

      - name: Run tests
        run: |
          python flask_app.py
          poetry run pytest

  second-ob:
    runs-on: windows-latest
    steps:
      - name: Print greetings form job nr 2
        run: echo "Hello world from job nr 2"

  
  
